spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chensongxian/config-repo/
#          search-paths: repo
          username:chensongxian
          password:csx13786564808

server:
  port: 1201